export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_TARGET_USER = 'SET_TARGET_USER';
export const SET_SUGGESTIONS = 'SET_SUGGESTIONS';
export const SET_DASHBOARD_POSTS = 'SET_DASHBOARD_POSTS';
export const SET_TARGET_POST_ID = 'SET_TARGET_POST_ID';
